#!/usr/bin/env bash

cd /inf4019-project2
git pull origin master > /dev/null 2>&1

cat /inf4019-project2/output.txt | grep -q '^test2_status="PASS"'
if [ $? -eq 0 ]; then
        #echo 'test2_status="PASS"'
	exit 0
else
        #echo 'test2_status="FAIL"'
	exit 1
fi
